version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/sheetah/main.go
    binary: sheetah
    ldflags:
      - -s -w
      - -X main.Version=v{{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
