name: Go
on: [push, pull_request]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Build & Test
      run: |
        go test -race ./...
